version: '3.3'

services:
  survey_db:
    container_name: survey_db
    image: postgis/postgis:latest
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - survey_db:/var/lib/postgresql/data

  survey_web:
    container_name: survey_web
    build: ./backend
    ports:
      - 8000:8000
    command: sh -c "gunicorn backend.wsgi:application -b 0.0.0.0:8000 --reload -t 120"
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app/

  survey_redis:
    container_name: survey_redis
    image: redis:alpine
    volumes:
      - "./redis-data:/data"

  survey_celery:
    container_name: survey_celery
    build: ./backend/
    command: celery -A backend worker -l info
    volumes:
      - ./backend/:/app/
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - survey_redis

  survey_front:
    container_name: survey_front
    build: ./frontend
    ports:
      - 8080:8080
    command: sh -c "npm run serve"
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - survey_web
    volumes:
      - ./frontend/:/app/

volumes:
  survey_db:
    driver: local
