version: '3.3'

services:  
  survey_web:
    container_name: survey_web
    build: 
      dockerfile: Dockerfile.prod
      context: ./backend
    ports:
      - 8000:8000
    command: sh -c "gunicorn -c gunicorn.py backend.wsgi"
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app/

  survey_redis:
    container_name: survey_redis
    image: redis:alpine

  survey_celery:
    container_name: survey_celery
    build: ./backend/
    command: celery -A backend worker -l info
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - survey_redis
    volumes:
      - ./backend/:/app/

  survey_front:
    container_name: survey_front
    build: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/app/
    command: npm run build
