version: '3.3'

services:  
  survey_web:
    container_name: survey_web
    build: 
      dockerfile: Dockerfile.prod
      context: ./backend
    ports:
      - 8001:8001
    command: sh -c "gunicorn -c gunicorn.py backend.wsgi"
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app/

  survey_front:
    container_name: survey_front
    build: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/app/
    command: npm run build
